# foo = "bar"

[modes.test]
name = "testconfig"
description = "This is a test config"
database = "test"

[modes.staging]
name = "stagingconfig"
description = "This is a staging config"
database = "test"

[modes.production]
name = "productionconfig"
description = "This is a production config"
database = "docker"

[databases.test]
name = "testdb"
auth_uri = "mongodb://user:password@localhost:27017/test"

[databases.docker]
name = "test_cyhy"
auth_uri = "mongodb://db:27017/cyhy"
